[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mars-lang"
version = "0.1.0"
description = "MARS robotics language and VM"
requires-python = ">=3.10"

dependencies = [
    "graphviz==0.20.1",
    "networkx==3.2.1",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["mars*"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"mars.mars_lang.templates" = ["**/*"]

[project.scripts]
mars = "mars.mars_lang.cli:main"