from typing import List, Tuple
import ast_nodes as ast

Instr = Tuple[str, ...] # instruction is a tuple of strings and then somtimes numbers. (Ex. ("PUSH_INT", 42) or ("ADD",) )

#This returns a List of instructions (bytecode) from the AST, and will give them to the Stack VM.
def compile_program(node: ast.Program, printBytecode = False) -> List[Instr]:
    code = []
    for stmt in node.statements:
        compile_node(stmt, code)
    code.append(("HALT",)) # this is for the ending of the program (so we know when to stop)
    if printBytecode:
        print_bytecode(code)
    return code

def compile_node(node, code: List[Instr]):
    """Emit bytecode for a single AST node appending into code list."""
    match node:
        case ast.NumberLiteral(value):
            if isinstance(value, int):
                code.append(("PUSH_INT", value))
            else:
                code.append(("PUSH_FLOAT", float(value)))

        case ast.StringLiteral(value):
            code.append(("PUSH_STR", value))

        case ast.BinaryOp(op, left, right):
            # compile left then right (stack-based order)
            compile_node(left, code)
            compile_node(right, code)
            match op:
                case "PLUS":
                    code.append(("ADD",))
                case "MINUS":
                    code.append(("SUB",))
                case "MUL":
                    code.append(("MUL",))
                case "DIV":
                    code.append(("DIV",))
                case _:
                    raise NotImplementedError(op)

        case ast.Assign(name, value):
            compile_node(value, code)
            code.append(("STORE", name))

        case ast.Var(name):
            code.append(("LOAD", name))

        case ast.Print(expr):
            compile_node(expr, code)
            code.append(("PRINT",))

        case _:
            raise TypeError(f"Unknown AST node {node}")

def print_bytecode(bytecode: List[Instr]):
    print("Generated Bytecode:")
    for i, instr in enumerate(bytecode):
        print(f"{i:04}: {instr}")
    print("\n")
