// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'README',
    },
    {
      type: 'doc',
      id: 'overview',
    },
    {
      type: 'doc',
      id: 'quickstart',
    },

    {
      type: 'category',
      label: 'Compiler Internals',
      link: {
        type: 'doc',
        id: 'compiler-internals/index',
      },
      items: [
        'compiler-internals/lexer',
        'compiler-internals/parser',
        'compiler-internals/typechecker',
        'compiler-internals/bytecode',
        'compiler-internals/vm',
      ],
    },

    {
      type: 'category',
      label: 'Language',
      items: [
        'language-reference',
        'components',
        'requirements',
      ],
    },

    {
      type: 'category',
      label: 'Runtime & Standard Library',
      items: [
        'runtime',
        'stdlib',
      ],
    },

    {
      type: 'category',
      label: 'Other',
      items: [
        'tooling',
        'errors',
        'basic_bridge_test',
      ],
    },
  ],
};

export default sidebars;
